# Copyright (c) 2026, Alaiy and contributors
# For license information, please see license.txt
"""
The `generate_product_images` tool: a five-shot editorial image set, produced by
editing the product's real photo.

One of the two image steps this app ships. Both are always registered; the agent's
prompt is what decides which it calls — see agent_meta.py. Requires
`openrouter_api_key` in site_config.json.
"""

import base64

import frappe

from alaiy_os_agent_shopify_listing.tools import handlers as base
from alaiy_os_agent_shopify_listing.tools import images

# Image generation goes through OpenRouter's own Unified Image API
# (POST /api/v1/images) — see _generate_one_image.
_IMAGE_GEN_MODEL = "openai/gpt-image-1"

_MAX_SHOTS = 5


def _generate_one_image(api_key, prompt, reference_data_uri):
	"""One call to OpenRouter's Unified Image API. Returns (b64_json, media_type, usage)."""
	import requests

	payload = {"model": _IMAGE_GEN_MODEL, "prompt": prompt, "n": 1, "output_format": "png"}
	if reference_data_uri:
		payload["input_references"] = [
			{"type": "image_url", "image_url": {"url": reference_data_uri}}
		]

	resp = requests.post(
		"https://openrouter.ai/api/v1/images",
		headers={"Authorization": f"Bearer {api_key}"},
		json=payload,
		timeout=180,
	)
	if resp.status_code != 200:
		frappe.throw(f"Image generation failed ({resp.status_code}): {resp.text[:500]}")
	data = resp.json()
	image = data["data"][0]
	return image["b64_json"], image.get("media_type", "image/png"), data.get("usage", {})


def generate_product_images(briefs, item_code=None, reference_image_url=None, generate_images=False):
	"""
	Generate up to 5 editorial shots in one call via OpenRouter's Unified Image API
	(POST /api/v1/images — a dedicated OpenRouter endpoint, NOT the OpenAI Images
	REST API; confirmed live, the OpenAI SDK's images.generate / images.edit both
	404 against OpenRouter). Each of `briefs` is {"kind": ..., "brief": ...}; each
	is saved as its own public File. Returns {"images": [{kind, brief, url}, ...]} —
	copy that list verbatim into the final `images` array.

	Whether we generate at all is decided HERE, deterministically — not left to the
	model's judgement — by two gates:

	  1. There must be an ORIGINAL product photo to edit. For an item_code run that
	     is the listing's own primary photo (read from the Shopify Product Listing's
	     images table); for a URL-only product it is reference_image_url. If neither
	     exists we return an empty list and generate nothing — this agent never
	     invents a product from scratch. This gate is airtight: it holds regardless
	     of what the model passes.
	  2. Generation is opt-in per request: generate_images must be true. When an
	     original photo exists but the toggle is off, we return empty too.

	Every shot is generated by EDITING that original photo (passed as a base64
	input_reference), so the set stays grounded in the real piece. The photo is
	resolved once — a stored Frappe File is read directly, an external url is
	downloaded — because a '/files/...' path isn't publicly fetchable and some CDNs
	refuse fetches with no browser-like User-Agent (see images.reference_source).

	If openrouter_api_key isn't configured (and both gates pass), the model is told
	via the thrown message not to retry and to fall back to url=null placeholders
	instead of stalling the rest of the listing.
	"""
	# ── Gate 1 (airtight): resolve the original photo; no photo → no generation.
	reference = None
	if item_code and frappe.db.exists(base.LISTING_DOCTYPE, item_code):
		reference = base.primary_listing_image_url(
			frappe.get_doc(base.LISTING_DOCTYPE, item_code)
		)
	if not reference and reference_image_url:
		reference = reference_image_url
	if not reference:
		return {"images": [], "note": (
			"No original product photo exists for this product, so no images were "
			"generated — this agent never creates product imagery from scratch."
		)}

	# ── Gate 2: editorial images are opt-in per request.
	if not generate_images:
		return {"images": [], "note": (
			"An original product photo exists, but the generate_images toggle is "
			"off, so no images were generated."
		)}

	api_key = frappe.conf.get("openrouter_api_key")
	if not api_key:
		frappe.throw(
			"Image generation is not configured (set openrouter_api_key in "
			"site_config.json). Do NOT retry; return each image with url=null and "
			"its brief so the team can shoot or generate it manually."
		)

	reference_data_uri = images.reference_data_uri(reference)

	out = []
	total_tokens = 0
	for entry in briefs[:_MAX_SHOTS]:
		b64_data, media_type, usage = _generate_one_image(
			api_key, entry["brief"], reference_data_uri
		)
		total_tokens += usage.get("total_tokens", 0)

		url = images.save_public_image(
			f"listing-{entry['kind']}", base64.b64decode(b64_data), media_type
		)
		out.append({"kind": entry["kind"], "brief": entry["brief"], "url": url})

	# Surface cost via the executor's "_usage" convention so it lands in
	# OS Agent Run.image_tokens instead of vanishing from token accounting.
	return {"images": out, "_usage": {"image_tokens": total_tokens}}
