# Copyright (c) 2026, Alaiy and contributors
# For license information, please see license.txt
"""
The `generate_product_images` tool: a five-shot editorial image set, produced by
editing the product's real photo.

One of the two image steps this app ships. Both are always registered; the agent's
prompt is what decides which it calls — see agent_meta.py.

The rendering itself goes through Alaiy OS core's `ai_client` seam
(`llm.generate_image`), the same seam the agent's text turns use. This app holds
no provider credential and names no image model: on a managed bench the call is
served by the billing service, which owns the key and meters the spend; on a BYOK
bench core's default client uses that site's own `openrouter_api_key`.

Two halves, split across two stages. `generate_product_images` runs inside the
agent's run: it decides whether imagery happens at all, and queues it. The actual
rendering is `render_generated`, which runs later on the image queue — see
image_stage.py for why.
"""

import base64
from concurrent.futures import ThreadPoolExecutor

import frappe
from alaiy_os.engine import llm

from alaiy_os_agent_shopify_listing import image_stage
from alaiy_os_agent_shopify_listing.tools import handlers as base
from alaiy_os_agent_shopify_listing.tools import images

_MAX_SHOTS = 5

# The set is rendered concurrently — see render_generated. Five at a time matches
# _MAX_SHOTS, so a full set is one wave rather than a queue behind itself.
_RENDER_CONCURRENCY = 5

# What stage one puts on an image row that stage two has not produced yet. It is
# read by a human on the Desk form, so it says what is happening, not "queued".
_QUEUED_NOTE = "Being produced in the background; the image will appear here when ready."


def generate_product_images(briefs, item_code=None, reference_image_url=None, generate_images=False):
	"""
	Queue up to 5 editorial shots and return immediately. Each of `briefs` is
	{"kind": ..., "brief": ...}. Returns {"images": [{kind, brief, url}, ...]} —
	copy that list verbatim into the final `images` array.

	`url` comes back null: the shots are rendered after this run finishes, by
	image_stage.run_step, and attached to the listing then. That is by design — a
	five-shot set takes minutes, and holding the run open for it would block a
	worker that could be enriching other products. The rendering itself is
	render_generated() below, which goes through core's `ai_client` seam
	(llm.generate_image) and saves each result as its own public File.

	The exception is a URL-only product: it has no listing record for stage two to
	deliver into, so its images are rendered inline and come back with real urls.

	Whether we generate at all is decided HERE, deterministically — not left to the
	model's judgement — by two gates:

	  1. There must be an ORIGINAL product photo to edit. For an item_code run that
	     is the listing's own primary photo (read from the Shopify Product Listing's
	     images table); for a URL-only product it is reference_image_url. If neither
	     exists we return an empty list and generate nothing — this agent never
	     invents a product from scratch. This gate is airtight: it holds regardless
	     of what the model passes.
	  2. Generation is opt-in per request: generate_images must be true. When an
	     original photo exists but the toggle is off, we return empty too.

	Every shot is generated by EDITING that original photo (passed as a base64
	input_reference), so the set stays grounded in the real piece. The photo is
	resolved once — a stored Frappe File is read directly, an external url is
	downloaded — because a '/files/...' path isn't publicly fetchable and some CDNs
	refuse fetches with no browser-like User-Agent (see images.reference_source).

	If the site's AI client cannot generate images at all (and both gates pass),
	the model is told via the thrown message not to retry and to fall back to
	url=null placeholders instead of stalling the rest of the listing.
	"""
	# ── Gate 1 (airtight): resolve the original photo; no photo → no generation.
	reference = None
	if item_code and frappe.db.exists(base.LISTING_DOCTYPE, item_code):
		reference = base.primary_listing_image_url(
			frappe.get_doc(base.LISTING_DOCTYPE, item_code)
		)
	if not reference and reference_image_url:
		reference = reference_image_url
	if not reference:
		return {"images": [], "note": (
			"No original product photo exists for this product, so no images were "
			"generated — this agent never creates product imagery from scratch."
		)}

	# ── Gate 2: editorial images are opt-in per request.
	if not generate_images:
		return {"images": [], "note": (
			"An original product photo exists, but the generate_images toggle is "
			"off, so no images were generated."
		)}

	# Checked here, while the model is still listening, rather than leaving it to
	# discover a misconfigured site minutes later in the background. Only the
	# capability is checked, not a credential — the credential lives off-bench now,
	# behind the seam, so this app has nothing to inspect.
	if not llm.image_client().image_support().get("generate"):
		frappe.throw(
			"Image generation is not available on this site (the active AI client "
			"cannot generate images). Do NOT retry; return each image with url=null "
			"and its brief so the team can shoot or generate it manually."
		)

	shots = [{"kind": entry["kind"], "brief": entry["brief"]} for entry in briefs[:_MAX_SHOTS]]

	# A URL-only product has no Shopify Enriched Listing for stage two to patch, so
	# there is nowhere to deliver the images later — render them inline, as before.
	if not item_code:
		result = render_generated(None, {"reference": reference, "briefs": shots})
		return {
			"images": result["images"],
			# The executor's "_usage" convention, so image cost lands in the Run.
			"_usage": {"image_tokens": result["image_tokens"]},
		}

	image_stage.queue_step(
		item_code,
		image_stage.GENERATE,
		{"reference": reference, "briefs": shots},
	)
	return {
		"images": [
			{
				"kind": shot["kind"],
				"brief": shot["brief"],
				"source_url": reference,
				"url": None,
				"note": _QUEUED_NOTE,
			}
			for shot in shots
		],
		"note": (
			f"{len(shots)} image(s) queued. They are being produced in the background "
			"and will be attached to this listing when they are ready — this is normal "
			"and is NOT a failure. Copy these entries verbatim, leave url as null, and "
			"do NOT record them in needs_review."
		),
	}


def render_generated(item_code, work):
	"""Produce the queued image set. Stage two's worker — see image_stage.py.

	Returns {"images": [{kind, brief, url, note}, ...], "image_tokens": int}; an
	entry whose generation failed comes back with url=None and a note, so one bad
	shot costs one image rather than the whole set.

	The shots are generated concurrently. They are five independent calls to a
	service that takes about a minute each, and running them in sequence was the
	single largest cost in the whole enrichment.
	"""
	# Both resolved on THIS thread, before the pool starts: the client reads site
	# config and the Frappe hook registry, and the reference reads a File row or
	# downloads the photo. Neither is possible inside a worker thread, which has no
	# Frappe request context — the client instance itself is thread-safe by
	# contract once built (see alaiy_os/engine/ai_client.py).
	client = llm.image_client()
	reference_data_uri = images.reference_data_uri(work["reference"])
	shots = work["briefs"]

	with ThreadPoolExecutor(max_workers=min(_RENDER_CONCURRENCY, len(shots) or 1)) as pool:
		results = list(
			pool.map(
				lambda shot: _try_generate(client, shot, reference_data_uri),
				shots,
			)
		)

	out = []
	total_tokens = 0
	for shot, (payload, error) in zip(shots, results, strict=True):
		if error:
			# Logged here rather than in the worker thread: frappe.log_error needs
			# the request context that only this thread has.
			frappe.log_error(
				title="Shopify listing: image generation failed",
				message=f"{item_code} / {shot['kind']}\n{error}",
			)
			out.append({
				"kind": shot["kind"],
				"brief": shot["brief"],
				"url": None,
				"note": f"Generation failed: {error}"[:200],
			})
			continue

		total_tokens += (payload.get("usage") or {}).get("total_tokens", 0)
		# Saving writes a File row, so it stays on this thread too.
		url = images.save_public_image(
			f"listing-{shot['kind']}",
			base64.b64decode(payload["b64"]),
			payload.get("media_type") or "image/png",
		)
		out.append({"kind": shot["kind"], "brief": shot["brief"], "url": url, "note": None})

	return {"images": out, "image_tokens": total_tokens}


def _try_generate(client, shot, reference_data_uri):
	"""One shot, in a worker thread. Returns (payload, error) — never raises.

	Nothing in here touches Frappe: the thread has no request context, so a
	frappe.throw or a db read from inside it would fail in a confusing way. The
	client was built on the calling thread and is thread-safe by contract.
	"""
	try:
		return client.generate_image(
			shot["brief"], reference_data_uri=reference_data_uri
		), None
	except Exception as exc:
		return None, str(exc)
